# Generated by Django 3.2.5 on 2022-02-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_bloghome'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloghome',
            name='slu',
            field=models.SlugField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
