# Generated by Django 3.2.5 on 2022-02-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_bloghome_slu'),
    ]

    operations = [
        migrations.CreateModel(
            name='prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botlength', models.TextField(max_length=3)),
                ('botdiameter', models.TextField(max_length=3)),
                ('bottype', models.TextField(max_length=50)),
            ],
        ),
    ]
